@startuml{update_study_time_activity.png}
start
:科目名・勉強時間・日付データを受け取る;
:科目名から科目IDを取得する;
if (日付データの時間が0時〜4時) then (yes)
  :日付データの日にちを-1する;
endif
:日付データの時間分秒を0にする;
:科目ID、日付データを使ってIDを取得する;
if (IDが取得できない)
  :IDを既存データのIDの最大値にする;
endif
:ID、科目ID、日付データ、勉強時間を勉強時間スキーマに登録・上書き処理をする;
stop

@enduml
